### ISSUE TITLE
Logout button doesn't work

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/checkout#60]
**Describe the bug**
Sometimes the logout button from checkout doesn't work. Redirects to "Personal data" and redirect back without Logging out the user. Maybe on "Personal data" checks cookies or cache and the user is logged in again. Sometimes it works, but sometimes not.

**To Reproduce**

1. Go to 'https://distinctive.ro'
2. Login
3. Add something to cart
4. Go to checkout
5. Press "Nu esti tu? Iesi din cont" button

**Screenshots**
[Video Here](https://youtu.be/NAU1K1qhjTI)

- All devices

**Comment by khrizzcristian** [comment]
Do you have any response regarding this issue?

**Comment by klzns** [comment]
Checkout issues are only handled via ticket.
